version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  module_system = "es-modules"

[[transformers]]
name = "standardjs"
enabled = true