name: '[Build] Compile TS to JS'
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16
      - name: Install dependencies for source code
        run:  npm run gh:install-dependencies
      - name: Build and push
        uses: alexthemaster/action-build-typescript@v1.2.1
        with:
          pushToBranch: true
          branch: 'main'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
