name: Check Markdown links

on:
  push:
    branches: [ 22T1 ]
  pull_request:
    branches: [ 22T1 ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
