name: "[Docs] Construir y publicar"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Construir documentación con Retype

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
